### ISSUE TITLE
Exclusions

### ISSUE THREAD

**Issue by IcePlains** [pedrocr/proxyswitcheroo#3]
Is there a way to use built-in exclusions list ("No Proxy for") or is there any other way to define excluded sites/ranges?
Would you be willing to implement it?

**Comment by pedrocr** [comment]
There is no support for anything that's not already in the settings. In the future I'll probably switch to the config API and then the extension becomes just an on/off switch to the settings you've already set in the Firefox config. And then you can have exclusions and any other stuff.

**Comment by pedrocr** [comment]
Version 1.0 is now on the extension store with this new way of working. I called it 1.0 because now it does everything I wanted. The permissions are still very small and yet all the possible proxy settings firefox supports can be set by just using the normal config. Testing and feedback is very welcome.

**Comment by IcePlains** [comment]
Seems to work as intended. Thank you :)
